from pathlib import Path
from os.path import join, realpath, dirname, exists
from os import makedirs, symlink

GLOBAL_API_CONFIG = {
    "bin": "kubectl",
    "configname": "ksx.json",
    "binpath": join(Path.home(), "bin"),
    "configpath": join(Path.home(), ".config", "ksx"),
    "cachepath": join(Path.home(), ".cache", "ksx"),
    "kctlpath": join(Path.home(), "bin", "kubectl"),
    "base_templates": ["simple_term_menu.py", "werbs.py", "api_res.py"],
    "conf": [
        {
            "name": "pods",
            "description": "Operate with pods",
            "template": "kstemplate.py",
            "filename": "ksp",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": True,
            "has_list": True,
            "has_output": True,
            "has_shell": True,
            "has_containers": True,
            "has_all_ns": True,
            "has_describe": True,
            "has_logs": True,
            "has_remove": True,
            "has_edit": True,
            "has_labels": True,
            "has_info": True
        },
        {
	    "name": "deployments",
            "description": "Operate with deployments",
            "template": "kstemplate.py",
	    "filename": "ksd",
            "has_current": False,
            "has_use": False,
            "has_scale": True,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": True,
	    "has_containers": True,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": True,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "sts",
            "description": "Operate with sts",
            "template": "kstemplate.py",
	    "filename": "ksts",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": True,
	    "has_containers": True,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": True,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "jobs",
            "description": "Operate with jobs",
            "template": "kstemplate.py",
	    "filename": "ksj",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": True,
	    "has_containers": True,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": True,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "cronjobs",
            "description": "Operate with cronjobs",
            "template": "kstemplate.py",
	    "filename": "kscj",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": True,
	    "has_containers": True,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": True,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "configmaps",
            "description": "Operate with configmaps",
            "template": "kstemplate.py",
	    "filename": "kscm",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": True,
	    "has_containers": True,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": True,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "ingress",
            "description": "Operate with ingress",
            "template": "kstemplate.py",
	    "filename": "ksi",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": True,
	    "has_containers": True,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": True,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "pv",
            "description": "Operate with pv",
            "template": "kstemplate.py",
	    "filename": "kspv",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": True,
	    "has_containers": True,
	    "has_all_ns": False,
	    "has_describe": True,
	    "has_logs": True,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "pvc",
            "description": "Operate with pvc",
            "template": "kstemplate.py",
	    "filename": "kspvc",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": True,
	    "has_containers": True,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": True,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "svc",
            "description": "Operate with svc",
            "template": "kstemplate.py",
	    "filename": "kss",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": True,
	    "has_containers": True,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": True,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "endpoints",
            "description": "Operate with endpoints",
            "template": "kstemplate.py",
	    "filename": "ksep",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "limits",
            "description": "Operate with limits",
            "template": "kstemplate.py",
	    "filename": "ksl",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "nodes",
            "description": "Operate with nodes",
            "template": "kstemplate.py",
	    "filename": "ksno",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": True,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": False,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "quota",
            "description": "Operate with quotas",
            "template": "kstemplate.py",
	    "filename": "ksq",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "daemonsets",
            "description": "Operate with daemonsets",
            "template": "kstemplate.py",
	    "filename": "ksds",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "replicasets",
            "description": "Operate with replicasets",
            "template": "kstemplate.py",
	    "filename": "ksrs",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "certificaterequests",
            "description": "Operate with certificaterequests",
            "template": "kstemplate.py",
	    "filename": "ksctreq",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "certificates",
            "description": "Operate with certificates",
            "template": "kstemplate.py",
	    "filename": "ksct",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": True,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "events",
            "description": "Operate with events",
            "template": "kstemplate.py",
	    "filename": "ksev",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": True,
	    "has_describe": False,
	    "has_logs": False,
	    "has_remove": False,
	    "has_edit": False,
	    "has_labels": False,
	    "has_info": False
        },
        {
	    "name": "namespaces",
            "description": "Operate with namespaces",
            "template": "ksnstemplate.py",
	    "filename": "ksn",
            "has_current": True,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": True,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": False,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": True,
	    "has_edit": True,
	    "has_labels": True,
	    "has_info": True
        },
        {
	    "name": "context",
            "description": "Operate with context",
            "template": "ksctxtemplate.py",
	    "filename": "ksc",
            "has_current": True,
            "has_use": True,
            "has_scale": False,
            "has_top": False,
	    "has_list": True,
	    "has_output": False,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": True,
	    "has_describe": False,
	    "has_logs": False,
	    "has_remove": False,
	    "has_edit": False,
	    "has_labels": False,
	    "has_info": False
        },
        {
	    "name": "config",
            "description": "Operate with kubectl config",
            "template": "ksconftemplate.py",
	    "filename": "ksconf",
            "has_current": False,
            "has_use": False,
            "has_scale": False,
            "has_top": False,
	    "has_list": False,
	    "has_output": False,
	    "has_shell": False,
	    "has_containers": False,
	    "has_all_ns": False,
	    "has_describe": True,
	    "has_logs": False,
	    "has_remove": False,
	    "has_edit": False,
	    "has_labels": False,
	    "has_info": False
        }
    ]
}
