GLOBAL_API_CONFIG =
[
    {
        "name": "pods",
        "filename": "ksp",
        "has_list": True,
        "has_output": True,
        "has_shell": True,
        "has_containers": True,
        "has_all_ns": True,
        "has_describe": True,
        "has_logs": True,
        "has_remove": True,
        "has_edit": True,
        "has_labels": True,
        "has_info": True
    },
    {
	"name": "deployments",
	"filename": "ksd",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "sts",
	"filename": "ksts",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "jobs",
	"filename": "ksj",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "cronjobs",
	"filename": "kscj",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "configmaps",
	"filename": "kscm",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "ingress",
	"filename": "ksi",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "pv",
	"filename": "kspv",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "pvc",
	"filename": "kspvc",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "svc",
	"filename": "kss",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "endpoints",
	"filename": "ksep",
	"has_list": True,
	"has_output": True,
	"has_shell": False,
	"has_containers": False,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": False,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    }
]
