GLOBAL_API_CONFIG = [
    {
        "name": "pods",
        "description": "Operate with pods",
        "filename": "ksp",
        "has_list": True,
        "has_output": True,
        "has_shell": True,
        "has_containers": True,
        "has_all_ns": True,
        "has_describe": True,
        "has_logs": True,
        "has_remove": True,
        "has_edit": True,
        "has_labels": True,
        "has_info": True
    },
    {
	"name": "deployments",
        "description": "Operate with deployments",
	"filename": "ksd",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "sts",
        "description": "Operate with sts",
	"filename": "ksts",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "jobs",
        "description": "Operate with jobs",
	"filename": "ksj",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "cronjobs",
        "description": "Operate with cronjobs",
	"filename": "kscj",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "configmaps",
        "description": "Operate with configmaps",
	"filename": "kscm",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "ingress",
        "description": "Operate with ingress",
	"filename": "ksi",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "pv",
        "description": "Operate with pv",
	"filename": "kspv",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "pvc",
        "description": "Operate with pvc",
	"filename": "kspvc",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "svc",
        "description": "Operate with svc",
	"filename": "kss",
	"has_list": True,
	"has_output": True,
	"has_shell": True,
	"has_containers": True,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": True,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    },
    {
	"name": "endpoints",
        "description": "Operate with endpoints",
	"filename": "ksep",
	"has_list": True,
	"has_output": True,
	"has_shell": False,
	"has_containers": False,
	"has_all_ns": True,
	"has_describe": True,
	"has_logs": False,
	"has_remove": True,
	"has_edit": True,
	"has_labels": True,
	"has_info": True
    }
]
