#!/usr/bin/env python3

import os, sys, subprocess, argparse

sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

from os.path import join, realpath, dirname
from werbs import Werbs
from json import loads

parser = argparse.ArgumentParser()

parser.add_argument("use_context_pos", help="Use context as current", type=str, nargs='*')

# command arguments group
cagroup=parser.add_argument_group('Werb arguments')

# service arguments group
sagroup=parser.add_argument_group('Service arguments')

cagroup.add_argument('-l', '--list',
                    action='store_true',
                    dest='list',
                    help='Suppress Output'
                    )

cagroup.add_argument('-u', '--use-context',
                    type=str,
                    dest='use_context',
                    help='Use context as current'
                    )

sagroup.add_argument('-n', '--namespace',
                    type=str,
                    dest='namespace',
                    help='Switch to namespace'
                    )

sagroup.add_argument('-t', '--trace',
                    action='store_true',
                    dest='trace',
                    help='trace real kubectl commands'
                    )

sagroup.add_argument('-v', '--version',
                    action='store_true',
                    dest='version',
                    help='show version of application'
                    )

kctl_bin = "/dev/null"

config=join(dirname(dirname(realpath(__file__))), 'ksx.json')

with open(config, 'r') as f:
    json = loads(f.read())
    kctl_bin = json['cmd'] if json['cmd'] else 'kubectl'

werbs = Werbs(config_path=config, kctl_bin=kctl_bin)

args = parser.parse_args()

def pit(string):
    global args
    if args.trace:
        print("cmd: `{}`".format(string))


def current_context():
    global kctl_bin
    cmd = kctl_bin + " config current-context" # get-contexts -o name
    pit(cmd)
    curr = subprocess.getoutput(cmd)
    return curr


def list_contexts():
    global kctl_bin
    cmd = kctl_bin + " config get-contexts -o name"
    pit(cmd)
    lst = subprocess.getoutput(cmd)
    return lst


def print_contexts():
    global kctl_bin
    cmd = kctl_bin + " config get-contexts"
    pit(cmd)
    subprocess.call(cmd, shell=True)


def set_current_context(ctx):
    global kctl_bin
    cmd = kctl_bin + " config use-context {}".format(ctx)
    pit(cmd)
    subprocess.call(cmd, shell=True)


if args.list:
    print_contexts()
elif args.use_context:
    set_current_context(args.use_context)
    if args.namespace:
        cmd = join(dirname(realpath(__file__)), 'ksn') + " {}".format(args.namespace)
        pit(cmd)
        subprocess.call(cmd, shell=True)
elif args.version:
    werbs.print_version()
elif args.use_context_pos:
    set_current_context(args.use_context_pos[0])
    if args.namespace:
        cmd = join(dirname(realpath(__file__)), 'ksn') + " {}".format(args.namespace)
        pit(cmd)
        subprocess.call(cmd, shell=True)
else:
    print(current_context())

