#!/usr/bin/env python

## This file $filename is autogenerated
## do not edit it, if you do not know
## what you do

import os,sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
# from api_res import ApiRes

def main ():
    res = ApiRes("$name",
                 description="$description",
                 config="$config",
                 has_list=$has_list,
                 has_output=$has_output,
                 has_shell=$has_shell,
                 has_containers=$has_containers,
                 has_all_ns=$has_all_ns,
                 has_describe=$has_describe,
                 has_logs=$has_logs,
                 has_remove=$has_remove,
                 has_edit=$has_edit,
                 has_labels=$has_labels,
                 has_info=$has_info,
                 has_top=$has_top,
                 has_scale=$has_scale,
                 has_use=$has_use,
                 has_current=$has_current)
    res.run()

if __name__ == "__main__":
    main()
