#!/usr/bin/env python3

import os, sys, subprocess, argparse

sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

from werbs import Werbs
from os.path import join, realpath, dirname

parser = argparse.ArgumentParser()

parser.add_argument("use_namespace_pos", help="Use namespace as current", type=str, nargs='*')

# command arguments group
cagroup=parser.add_argument_group('Werb arguments')

# service arguments group
sagroup=parser.add_argument_group('Service arguments')

cagroup.add_argument('--list',
                    action='store_true',
                    dest='list',
                    help='Suppress Output'
                    )

cagroup.add_argument('-c', '--current',
                    action='store_true',
                    dest='current',
                    help='Print current namespace'
                    )

sagroup.add_argument('-o', '--output',
                    type=str,
                    dest='output',
                    help='output format json|yaml|wide|custom-columns=...|custom-columns-file=...|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...]'
                    )

cagroup.add_argument('-u', '--use-namespace',
                    type=str,
                    dest='use_namespace',
                    help='Use namespace as current'
                    )

cagroup.add_argument('-d', '--describe',
                    type=str,
                    dest='describe',
                    help='describe namespace'
                    )

cagroup.add_argument('-e', '--edit',
                    type=str,
                    dest='edit',
                    help='edit pvc'
                    )

sagroup.add_argument('-t', '--trace',
                    action='store_true',
                    dest='trace',
                    help='trace real kubectl commands'
                    )

sagroup.add_argument('-v', '--version',
                    action='store_true',
                    dest='version',
                    help='show version of application'
                    )

cagroup.add_argument('--wat',
                    action='store_true',
                    dest='wat',
                    help='Manual about kubernetes PVC'
                    )

sagroup.add_argument('-l', '--labels',
                    type=str,
                    dest='labels',
                    help='Use label to filter out resources'
                    )

args = parser.parse_args()

global out_suffix, kctl_bin, werbs

kctl_bin = "kubectl"

if args.output:
    out_suffix = " -o " + args.output
else:
    out_suffix = ""

config=join(dirname(dirname(realpath(__file__))), 'ksx.json')

werbs = Werbs(config_path=config, out_format=args.output,
              labels=args.labels, kctl_bin=kctl_bin, trace=args.trace)


global labels
labels = ''
if args.labels:
    labels = " -l " + labels

def set_current_namespace(ns):
    curr_context = werbs.current_context()
    cmd = "kubectl config set-context {} --namespace {}".format(curr_context, ns)
    if args.trace:
        ns = werbs.current_namespace()
        ctx = werbs.current_context()
        print("cmd: `{}`; namespace: `{}`; context: `{}`".format(cmd, ns, ctx))

    subprocess.call(cmd, shell=True)


if args.list:
    werbs.print_of("namespaces")
elif args.use_namespace:
    set_currenyt_namespace(args.use_namespace)
elif args.describe:
    werbs.describe_of("namespaces/{}".format(args.describe))
elif args.edit:
    werbs.edit_of("namespace/{}".format(args.edit))
elif args.wat:
    werbs.explain_of("namespaces")
elif args.version:
    werbs.print_version()
elif args.use_namespace_pos:
    if args.use_namespace_pos[0] == '-':
        set_current_namespace(args.use_namespace_pos[0])
    else:
        set_current_namespace(args.use_namespace_pos[0])
elif args.current:
    print(werbs.current_namespace())
else: # default action is "get namespaces"
    werbs.print_of("namespaces")
