#!/usr/bin/env python3

import subprocess, argparse
from werbs import Werbs

parser = argparse.ArgumentParser()

parser.add_argument("describe_pod_pos", help="Get pod", type=str, nargs='*')

parser.add_argument('-l', '--list',
                    action='store_true',
                    dest='list',
                    help='Suppress Output'
                    )

parser.add_argument('-o', '--output',
                    type=str,
                    dest='output',
                    help='output format json|yaml|wide|custom-columns=...|custom-columns-file=...|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...]'
                    )

parser.add_argument('-s', '--shell',
                    type=str,
                    dest='shell',
                    help='Run shell on a selected pod'
                    )

parser.add_argument('--cl', '--containers-list',
                    type=str,
                    dest='containers_list',
                    help='Get list of pod`s running containers'
                    )

parser.add_argument('--container',
                    type=str,
                    dest='container_name',
                    help='Operate with single container inside of multicontainer pod'
                    )

parser.add_argument('-A', '--all-namespaces',
                    action='store_true',
                    dest='all_namespaces',
                    help='Operate with resources from all namespaces'
                    )

parser.add_argument('-d', '--describe',
                    type=str,
                    dest='describe',
                    help='describe namespace'
                    )

parser.add_argument('-t', '--trace',
                    action='store_true',
                    dest='trace',
                    help='trace real kubectl commands'
                    )

parser.add_argument('--labels',
                    type=str,
                    dest='labels',
                    help='Use label to filter out resources'
                    )

parser.add_argument('--wat',
                    action='store_true',
                    dest='wat',
                    help='Manual about kubernetes pods'
                    )

args = parser.parse_args()

global out_suffix, kctl_bin, werbs, pod_shell

kctl_bin = "kubectl"
pod_shell = "/bin/bash"

werbs = Werbs(out_format=args.output, labels=args.labels, kctl_bin=kctl_bin, all_ns=args.all_namespaces, trace=args.trace)

if args.output:
    out_suffix = " -o " + args.output
else:
    out_suffix = ""

def shell_to_pod(name):
    cmd = "{} exec --stdin --tty pods/{} -- {}".format(kctl_bin, name, pod_shell)
    subprocess.call(cmd, shell=True)

def shell_to_pods_container(pod_name, container_name):
    cmd = "{} exec --stdin --tty pods/{} --container {} -- {}".format(kctl_bin, pod_name, container_name, pod_shell)
    subprocess.call(cmd, shell=True)


def containers_list(name):
    cmd = "{} get pods/{}".format(kctl_bin, name)
    cmd += " -o=jsonpath='{.spec.containers[*].name}'"
    out = subprocess.getoutput(cmd)
    return out

    
if args.list:
    werbs.print_of("pods")
elif args.shell:
    if args.container_name:
        shell_to_pods_container(args.shell, args.container_name)
    else:
        shell_to_pod(args.shell)
elif args.containers_list:
    print(containers_list(args.containers_list))
elif args.describe:
    werbs.describe_of("pods/{}".format(args.describe))
elif args.wat:
    werbs.explain_of("pods")
elif args.describe_pod_pos:
    werbs.describe_of("pods/{}".format(args.describe_pod_pos[0]))
else: # default action is "get namespaces"
    werbs.print_of("pods")
