#!/usr/bin/env python3

import argparse
import subprocess

parser = argparse.ArgumentParser()

parser.add_argument('-l', '--list',
                    action='store_true',
                    dest='list',
                    help='Suppress Output'
                    )
parser.add_argument('-o', '--output',
                    type=str,
                    dest='output',
                    help='output format json|yaml|wide|custom-columns=...|custom-columns-file=...|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...]'
                    )

parser.add_argument('-c', '--current-svc',
                    action='store_true',
                    dest='current_svc',
                    help='Print current svc'
                    )

parser.add_argument('-u', '--use-svc',
                    type=str,
                    dest='use_svc',
                    help='Use svc as current'
                    )

args = parser.parse_args()

global out_suffix

if args.output:
    out_suffix = " -o " + args.output
else:
    out_suffix = ""


def list_svcs():
    cmd = "kubectl get svcs -o name" + out_suffix
    lst = subprocess.getoutput(cmd)
    return lst


def print_svcs():
    cmd = "kubectl get svc" + out_suffix
    subprocess.call(cmd, shell=True)

if args.list:
    print_svcs()
elif args.current_svc:
    print(get_current_svc())
elif args.use_svc:
    set_current_svc(args.use_svc)
else: # default action is "get svcs"
    print_svcs()
